modulus/sym/models/arch.py, modulus/sym/models/multiscale_fourier_net.py, modulus/sym/utils/training/stop_criterion.py
- Stop Criterion Bug Fix
- Fixing bug in instantiate arch
- Fixing multiscale fourier net default parameter bug
=> Forums bugs

examples/anti_derivative/data_informed.py, examples/anti_derivative/physics_informed.py, examples/limerock/limerock_transfer_learning/limerock_flow.py
Hot-fix for fourier net instantiation
=> Hot-Fix Instantiate architectures explicitly

CONTRIBUTING.md, README.md
Updated contribution guidelines and readme
=> Updated contribution guidelines

modulus/sym/loss/aggregator.py, pyproject.toml
- Adding missing dependency in TOML
=> Pyproject Update

modulus/sym/eq/pdes/navier_stokes.py
Closes #22 
Add missing terms in the implemented Navier Stokes equation as discussed in the issue.
=> fix: add missing terms in NS equation

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/PULL_REQUEST_TEMPLATE.md, .gitlab/merge_request_templates/Default.md, .markdownlint.yaml, .pre-commit-config.yaml, CHANGELOG.md, CONTRIBUTING.md, Makefile, README.md, examples/test/README.md
* Adding pre-commit
* Markdown linter added
* Adding Github templates
* Adding change log
=> Enh: Adding Markdown Linter and Pre-commit

modulus/sym/constants.py, modulus/sym/hydra/arch.py, modulus/sym/models/arch.py
Long term fix for the eval usage in the configs
=> Fixes the arch configs and updates the pytorch version in constants

CHANGELOG.md, modulus/sym/models/arch.py, test/test_models/test_activation.py
Fixing test to also filter cuLaunchKernel in addition to cudaLaunchKernel
None
=> Fixing FusedSiLU tests

examples/annular_ring/annular_ring_gradient_enhanced/conf/config.yaml
Reduces batch size for gradient enhanced Annular ring example. 
=> Reduce batch size for gradient enhanced annular ring

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/sym/__init__.py, pyproject.toml
Update version for Modulus Core and Sym
=> Version update 1.1.0

CHANGELOG.md, modulus/sym/trainer.py
=> Rebase 0.2.0-rc into main

.github/PULL_REQUEST_TEMPLATE.md, CHANGELOG.md, modulus/sym/__init__.py
Closes: https://github.com/NVIDIA/modulus-sym/issues/46
=> Updating main version to pre-release

examples/test/run_experiments.py
=> Update experiments runner

examples/darcy/conf/config_DeepO.yaml
Updates Darcy DeepONet configs to latest conventions as per: https://github.com/NVIDIA/modulus-sym/pull/41
Closes: https://github.com/NVIDIA/modulus-sym/issues/61
=> Update Darcy DeepONet: Update Fourier net configs to latest conventions

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/sym/__init__.py
=> Version update 1.2.0

.github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/documentation_request.yml, .github/ISSUE_TEMPLATE/feature_request.yml, CHANGELOG.md, README.md, examples/darcy/conf/config_DeepO.yaml, modulus/sym/__init__.py
=> 1.2.0 rc rebase

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/sym/__init__.py
=> 1.4.0 Version Update

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, README.md, modulus/sym/__init__.py, pyproject.toml, test/test_models/test_activation.py
=> 1.4.0 rc rebase

examples/README.md, examples/chip_2d/chip_2d_solid_fluid_heat_transfer_heat.py
- Adds hyperlink to each example entry in master readme
- Adds links to Core's examples
Closes: https://github.com/NVIDIA/modulus-sym/issues/109
=> README updates 02152024

examples/reservoir_simulation/README.md
Add a summarized Readme for reservoir examples folder.
=> Add master readme for reservoir examples

.github/workflows/blossom-ci.yml
Updates the workflow file based on latest guidance.
=> Make the user check exact

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/sym/__init__.py
Release prep for 1.6.0 release
=> Update versions for 1.6.0 release

CHANGELOG.md, examples/super_resolution/inference_utils.py
Adds inference analysis for the turbulent super resolution example.
=> Add inference analysis for the turbulence super resolution example

.github/workflows/blossom-ci.yml
Adding @Alexey-Kamenev to list of authorized CI users.
=> Add new CI user

CHANGELOG.md
=> Fix changelog addition

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, Dockerfile, README.md, docs/conf.py, examples/super_resolution/inference_utils.py, modulus/sym/__init__.py, modulus/sym/geometry/tessellation.py
Release testing for 1.6.0 is ongoing, but rebasing currently to include the Warp tessellation change to the main branch to unblock [#160](https://github.com/NVIDIA/modulus-sym/pull/160)
=> 1.6.0 rc rebase into main (first rebase)

examples/reservoir_simulation/2D/requirements.txt, examples/reservoir_simulation/3D/requirements.txt, examples/reservoir_simulation/Norne/requirments.txt
Remove the hard requirement for versions in the requirements.txt for the reservoir examples. This was found in internal testing [here](https://nvbugspro.nvidia.com/bug/4748239).
=> Update tf in requirements.txt for reservoir examples

CHANGELOG.md, pyproject.toml
Some of our dependencies require Python 3.10+ and this is also the version inside our Docker containers.
=> Update required python version to 3.10

CHANGELOG.md, Dockerfile, pyproject.toml
Updates package versions for sympy and scikit-learn to fix build issues
=> Update package versions for sympy and scikit-learn

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/sym/__init__.py
Update versions for 1.7.0 release preparation.
=> Update versions for 1.7.0 release

README.md
Update the pip install command after update to the pypi registry
=> Update pip install command

examples/reservoir_simulation/2D/README.md, examples/reservoir_simulation/3D/README.md
Add a note about the container to use for the reservoir examples.
=> Update the docs for the reservoir example

.github/ISSUE_TEMPLATE/bug_report.yml, CHANGELOG.md, modulus/sym/__init__.py
=> Update versions for 1.8.0

.github/workflows/blossom-ci.yml
Add saikrishnanc-nv to blossom CI's GitHub actors.
=> Add saikrishnanc-nv to blossom github actors

.gitlab-ci.yml, sonar-project.properties
Setup for Sonar Qube code scans.
=> Sonar setup
